### PR TITLE
limit swap partition size to 8 GiB

### PR DESCRIPTION
**Pull request by fraenki**
I had an interesting experience: I've installed OPNsense on a server with 32 GiB RAM and a 128 GiB SSD as boot device. This resulted in a whopping **64 GiB swap partition**! Not useful at all. This should not be the result of the default/easy installation.

The initial swap partition should be sort of a last resort and thus be rather small. I suggest to limit it's size to 4 GiB. It's still possible to add additional swap files later, if the need arises, and I think this should be the preferred way.

### CODE REVIEW

**Comment by fichtner** [comment]
The swap calculation is probably from the i386 days. Capping seems reasonable, but I’m not sure about 4GB as the recommended value was always 2 times RAM, which for i386 creates a max of 8GB.

So from a historical standpoint we do not only cap the swap size, but we reduce its old maximum by half.

Change to 8GB?

**Comment by fraenki** [comment]
> Change to 8GB?

A good compromise. Although, if a server actually _uses_ this amount of swap space, it's pretty much useless anyway ;)

**Comment by fraenki** [comment]
Changed it to 8 GiB in https://github.com/opnsense/bsdinstaller/pull/8/commits/e8681c1ca1b506a4669e3e1b60dbf87d5d6206b8.

**Comment by fichtner** [comment]
Merged, thanks.

Someone else in the forum asked for the same issue. What do you think about asking for swap creation but still set the default to use a swap? This way we could also tell people a swap can’t be created because too small.

**Comment by fraenki** [comment]
> What do you think about asking for swap creation but still set the default to use a swap?

It's always good to have a choice. So yes, asking this question during installation would certainly be an improvement.

**Comment by fichtner** [comment]
Ok, I’ll give this more thought. Thanks for the input. :)

**Comment by fichtner** [comment]
https://github.com/opnsense/bsdinstaller/issues/10

**Pull request merged**
